### ISSUE TITLE
does not build with ubuntu 22.04 / llvm-config-14

### ISSUE THREAD

**Issue by lambdafu** [aflnet/aflnet#81]
Hi,

trying to build on Ubuntu 22.04 with:

```
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y build-essential git clang graphviz-dev

ENV LLVM_CONFIG=llvm-config-14

RUN git clone https://github.com/aflnet/aflnet && \
    cd aflnet && \
    make clean all && \
    cd llvm_mode make && make
```

I get the following error:

```
clang++ `llvm-config-14 --cxxflags` -Wl,-znodelete -fno-rtti -fpic -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"2.56b\" -Wno-variadic-macros -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config-14 --ldflags`
afl-llvm-pass.so.cc:52:30: error: expected class name
  class AFLCoverage : public ModulePass {
                             ^
afl-llvm-pass.so.cc:59:35: error: only virtual member functions can be marked 'override'
      bool runOnModule(Module &M) override;
                                  ^~~~~~~~
afl-llvm-pass.so.cc:57:23: error: member initializer 'ModulePass' does not name a non-static data member or base class
      AFLCoverage() : ModulePass(ID) { }
                      ^~~~~~~~~~~~~~
afl-llvm-pass.so.cc:134:31: error: no matching member function for call to 'CreateLoad'
      LoadInst *PrevLoc = IRB.CreateLoad(AFLPrevLoc);
                          ~~~~^~~~~~~~~~
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1659:13: note: candidate function not viable: requires 3 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
            ^
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1663:13: note: candidate function not viable: requires at least 2 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
            ^
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1667:13: note: candidate function not viable: requires at least 3 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
            ^
afl-llvm-pass.so.cc:140:30: error: no matching member function for call to 'CreateLoad'
      LoadInst *MapPtr = IRB.CreateLoad(AFLMapPtr);
                         ~~~~^~~~~~~~~~
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1659:13: note: candidate function not viable: requires 3 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
            ^
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1663:13: note: candidate function not viable: requires at least 2 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
            ^
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1667:13: note: candidate function not viable: requires at least 3 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
            ^
afl-llvm-pass.so.cc:143:15: error: no matching member function for call to 'CreateGEP'
          IRB.CreateGEP(MapPtr, IRB.CreateXor(PrevLocCasted, CurLoc));
          ~~~~^~~~~~~~~
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1735:10: note: candidate function not viable: requires at least 3 arguments, but 2 were provided
  Value *CreateGEP(Type *Ty, Value *Ptr, ArrayRef<Value *> IdxList,
         ^
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1749:10: note: candidate function not viable: requires at least 3 arguments, but 2 were provided
  Value *CreateGEP(Type *Ty, Value *Ptr, Value *Idx, const Twine &Name = "") {
         ^
afl-llvm-pass.so.cc:147:31: error: no matching member function for call to 'CreateLoad'
      LoadInst *Counter = IRB.CreateLoad(MapPtrIdx);
                          ~~~~^~~~~~~~~~
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1659:13: note: candidate function not viable: requires 3 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
            ^
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1663:13: note: candidate function not viable: requires at least 2 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
            ^
/usr/lib/llvm-14/include/llvm/IR/IRBuilder.h:1667:13: note: candidate function not viable: requires at least 3 arguments, but 1 was provided
  LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
            ^
afl-llvm-pass.so.cc:183:10: error: cannot initialize a parameter of type 'llvm::Pass *' with an rvalue of type '(anonymous namespace)::AFLCoverage *'
  PM.add(new AFLCoverage());
         ^~~~~~~~~~~~~~~~~
/usr/lib/llvm-14/include/llvm/IR/LegacyPassManager.h:48:26: note: passing argument to parameter 'P' here
  virtual void add(Pass *P) = 0;
                         ^
8 errors generated.
make: *** [Makefile:84: ../afl-llvm-pass.so] Error 1
```

**Comment by thuanpv** [comment]
We only tested the tool on Ubuntu 18.04 and 20.04 64-bit.

A quick look at your error message tells me that this is not an AFLNet-specific issue. In AFLNet, we did not make any changes to the llvm pass. You can try to compile the normal AFL on your setup first; if it works, the compilation of AFLNet should also work.

**Comment by vsysoev** [comment]
In case of LLVM-13 it turns to deprecated. 
```
afl-llvm-pass.so.cc:134:31: warning: 'CreateLoad' is deprecated: Use the version that explicitly specifies the loaded type instead [-Wdeprecated-declarations]
      LoadInst *PrevLoc = IRB.CreateLoad(AFLPrevLoc);
                              ^
/usr/lib/llvm-13/include/llvm/IR/IRBuilder.h:1678:3: note: 'CreateLoad' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(LoadInst *CreateLoad(Value *Ptr,
  ^
/usr/lib/llvm-13/include/llvm/Support/Compiler.h:320:52: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
#define LLVM_ATTRIBUTE_DEPRECATED(decl, message) [[deprecated(message)]] decl
                                                   ^
afl-llvm-pass.so.cc:140:30: warning: 'CreateLoad' is deprecated: Use the version that explicitly specifies the loaded type instead [-Wdeprecated-declarations]
      LoadInst *MapPtr = IRB.CreateLoad(AFLMapPtr);
                             ^
/usr/lib/llvm-13/include/llvm/IR/IRBuilder.h:1678:3: note: 'CreateLoad' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(LoadInst *CreateLoad(Value *Ptr,
  ^
/usr/lib/llvm-13/include/llvm/Support/Compiler.h:320:52: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
#define LLVM_ATTRIBUTE_DEPRECATED(decl, message) [[deprecated(message)]] decl
                                                   ^
afl-llvm-pass.so.cc:143:15: warning: 'CreateGEP' is deprecated: Use the version with explicit element type instead [-Wdeprecated-declarations]
          IRB.CreateGEP(MapPtr, IRB.CreateXor(PrevLocCasted, CurLoc));
              ^
/usr/lib/llvm-13/include/llvm/IR/IRBuilder.h:1787:3: note: 'CreateGEP' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(
  ^
/usr/lib/llvm-13/include/llvm/Support/Compiler.h:320:52: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
#define LLVM_ATTRIBUTE_DEPRECATED(decl, message) [[deprecated(message)]] decl
                                                   ^
afl-llvm-pass.so.cc:147:31: warning: 'CreateLoad' is deprecated: Use the version that explicitly specifies the loaded type instead [-Wdeprecated-declarations]
      LoadInst *Counter = IRB.CreateLoad(MapPtrIdx);
                              ^
/usr/lib/llvm-13/include/llvm/IR/IRBuilder.h:1678:3: note: 'CreateLoad' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(LoadInst *CreateLoad(Value *Ptr,
  ^
/usr/lib/llvm-13/include/llvm/Support/Compiler.h:320:52: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
#define LLVM_ATTRIBUTE_DEPRECATED(decl, message) [[deprecated(message)]] decl
                                                   ^
4 warnings generated.
```

**Comment by vsysoev** [comment]
Ubuntu 20.04 LLVM-12 built successfully.

**Comment by thuanpv** [comment]
Thanks for your update. As I suspected, the issue is in the LLVM pass which is the same for normal AFL and AFLNet.
